import './globals.css'

import { Fira_Code } from 'next/font/google'
import type { Metadata } from 'next'
import TRPCProvider from 'itsa/trpc/TRPCProvider'

const font = Fira_Code({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className} suppressHydrationWarning={true}>
        <TRPCProvider>{children}</TRPCProvider>
      </body>
    </html>
  )
}
