import './globals.css'

import { Fira_Code } from 'next/font/google'
import Header from 'itsa/components/layout/Header'
import type { Metadata } from 'next'
import Provider from '../components/provider'

const font = Fira_Code({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Provider>
        <body className={font.className} suppressHydrationWarning={true}>
          <Header />
          {children}
        </body>
      </Provider>
    </html>
  )
}
